[workspace]
authors = ["wuwenrui555 <wuwenruiwwr@outlook.com>"]
channels = ["conda-forge"]
name = "env_mesmer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
ipykernel = ">=6.29.5,<7"
poetry = ">=2.1.3,<3"
